### ISSUE TITLE
howlol

### ISSUE THREAD

**Issue by AydanAnimates** [Koischizo/AI-Vtuber#39]
I have no idea how to code and there so I can't even get past the github link. can someone please just tell me how to do it lol

**Comment by RaihanSW** [comment]
Its fine, as starter maybe you want to download the program first. so, after you click the link in the description

1. click on the "Koischizo" word beside the cat icon on the left top of this screen. It will navigate to list of repositories, which is the place where Koischizo save his code online (It can be analogical to folder drive but for code, and allow others to edit file in that folder)
2. Then, click on the repositories "AI-Vtuber". It shows all files used for the project
3. Afterwards, click the green "Code" button, and download as ZIP. Extract the ZIP after download and you may have the file needed for AI Vtuber in the video

The next step needs.... some knowledge of code, but no worry, no need to rush and maybe you may learn little of coding
Install a programming language called "python", you can find it here
https://www.python.org/

before clicking next, remember to check "add python to path" then just go next next next (by default, it will be installed in Drive C )

4. after finish installing python, go to the folder you download before and type "pip install -r requirements.txt" , It will install all library(or bunch of function to run the program) needed for the project

Im sorry that I can't tell the next step since I haven't tried it myself. but those 4 steps already covers the "Setup" section of the project (excluding ffmepg) , maybe others can help for the next step from "Usage" section

**Comment by AydanAnimates** [comment]
@RaihanSW In step 4 what folder do I go into and where do I type the command because I cant figure that out rn

**Comment by RaihanSW** [comment]
in step number 4, it means the folder of the program code you have download before from this github. I assume you download the zip directly, then the folder mentioned is the folder from zip extracted. for the command, you can open command prompt inside the folder (by right click and select "open command prompt") , or click the folder path then type "cmd". in the command prompt, type "pip install -r requirements.txt"

**Comment by AydanAnimates** [comment]
@RaihanSW Ok thanks, what do I do after that now? im rly confused ._.
